using Eap.Domain.Common;

namespace Eap.Domain.Requirements;

/// <summary>
/// One scheduled action a user owes for a specific cycle of an acknowledgment version
/// (docs/05-data/conceptual-data-model.md §8, BR-060..BR-063).
///
/// Records are generated by <c>IRequirementGenerator</c> and identified uniquely by the
/// combination (<see cref="UserId"/>, <see cref="AcknowledgmentVersionId"/>, <see cref="CycleReference"/>).
/// <see cref="IsCurrent"/> flags the latest open cycle — older cycles stay in the table
/// for audit and historical reporting.
/// </summary>
public sealed class UserActionRequirement : AuditableEntity
{
    // EF Core
    private UserActionRequirement() { }

    public UserActionRequirement(
        Guid userId,
        Guid acknowledgmentVersionId,
        string cycleReference,
        DateOnly? recurrenceInstanceDate,
        DateOnly? dueDate,
        DateTimeOffset assignedAtUtc,
        string? createdBy)
    {
        if (userId == Guid.Empty)
        {
            throw new ArgumentException("User id is required.", nameof(userId));
        }

        if (acknowledgmentVersionId == Guid.Empty)
        {
            throw new ArgumentException(
                "Acknowledgment version id is required.",
                nameof(acknowledgmentVersionId));
        }

        if (string.IsNullOrWhiteSpace(cycleReference))
        {
            throw new ArgumentException(
                "Cycle reference is required (e.g. 'onboarding', 'annual:2026').",
                nameof(cycleReference));
        }

        UserId = userId;
        AcknowledgmentVersionId = acknowledgmentVersionId;
        CycleReference = cycleReference.Trim();
        RecurrenceInstanceDate = recurrenceInstanceDate;
        DueDate = dueDate;
        AssignedAtUtc = assignedAtUtc;
        Status = UserActionRequirementStatus.Pending;
        IsCurrent = true;
        CreatedBy = createdBy?.Trim();
    }

    public Guid UserId { get; private set; }

    public Guid AcknowledgmentVersionId { get; private set; }

    /// <summary>Deterministic key for the cycle — e.g. "onboarding", "annual:2026",
    /// "event:ref", "change:ref" (BR-040..BR-047).</summary>
    public string CycleReference { get; private set; } = default!;

    /// <summary>Anchor date of the cycle instance — January 1st for annual, hire date
    /// for onboarding, occurrence date for event-driven. Nullable to tolerate
    /// cadences where no single date applies.</summary>
    public DateOnly? RecurrenceInstanceDate { get; private set; }

    public DateOnly? DueDate { get; private set; }

    public DateTimeOffset AssignedAtUtc { get; private set; }

    public DateTimeOffset? CompletedAtUtc { get; private set; }

    public UserActionRequirementStatus Status { get; private set; }

    /// <summary>True while this is the active cycle for the (user, version) pair.
    /// When a newer cycle is generated the previous row is flipped to false.</summary>
    public bool IsCurrent { get; private set; }

    public void MarkCompleted(DateTimeOffset whenUtc, string? completedBy)
    {
        if (Status == UserActionRequirementStatus.Completed)
        {
            return;
        }

        Status = UserActionRequirementStatus.Completed;
        CompletedAtUtc = whenUtc;
        UpdatedAtUtc = whenUtc;
        UpdatedBy = completedBy?.Trim();
    }

    public void MarkOverdue(DateTimeOffset whenUtc)
    {
        if (Status != UserActionRequirementStatus.Pending)
        {
            return;
        }

        Status = UserActionRequirementStatus.Overdue;
        UpdatedAtUtc = whenUtc;
    }

    public void Cancel(DateTimeOffset whenUtc, string? cancelledBy)
    {
        if (Status is UserActionRequirementStatus.Completed
                   or UserActionRequirementStatus.Cancelled)
        {
            return;
        }

        Status = UserActionRequirementStatus.Cancelled;
        IsCurrent = false;
        UpdatedAtUtc = whenUtc;
        UpdatedBy = cancelledBy?.Trim();
    }

    internal void MarkSupersededByNewerCycle(DateTimeOffset whenUtc)
    {
        if (!IsCurrent)
        {
            return;
        }

        IsCurrent = false;
        UpdatedAtUtc = whenUtc;
    }
}
